window.onload=function () {
/*    var json=[
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        }

    ];

    */
    var data=[];
    reqwest({
        url: 'php/getData.php?req=articleList',
        method: 'get',
        success: function(resp){
            if(resp.result=="success"){
                for(var a=0;a<resp.data.length;a++){
                    data.push(resp.data[a]);
                }
                for(var i=0;i<data.length;i++){
                    var cloneDiv= q("a.main-articles-a:first-child").cloneNode(true);
                    q("div.main").appendChild(cloneDiv);
                    cloneDiv.setAttribute("id","");
                    cloneDiv.setAttribute("href","index.php?id="+data[i].id);
                    cloneDiv.style.display="inline-block";
                    var HTML= cloneDiv.innerHTML;
                    HTML=HTML.replace("{{articles-desc}}",data[i].desp);
                    HTML=HTML.replace("{{imgURL}}",data[i].pic);
                    HTML=HTML.replace("{{name}}",data[i].writer);
                    HTML=HTML.replace("{{title}}",data[i].title);
                    HTML=HTML.replace("{{date}}",data[i].create_date.split(" ")[0]);
                    HTML=HTML.replace("{{pic}}","title1.jpg");
                    var num1=0;
                    var num2=0;
                    if(data[i].sub_articles==""){
                        num1=0;
                    }else{
                        num1=data[i].sub_articles.split(",").length;
                    }
                    if(data[i].like==""){
                        num2=0;
                    }else{
                        num2=data[i].like.split(",").length;
                    }
                    HTML=HTML.replace("{{num1}}",num1);
                    HTML=HTML.replace("{{num2}}",num2);
                    cloneDiv.innerHTML=HTML;
                }
            }else{
                alert("获取文章列表失败！");
            }
        }
    });
};
