window.onload=function () {
    var json=[
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        },
        {
            pic_url:"title1.jpg",
            link_url:"",
            title:"/php优于Node.js的几种理由",
            disc:"地方生活的如何不懂法规保护UI肉还不覅和戹",
            name:"Faraway",
            date:"",
            num1:111,
            num2:520
        }

    ];
    var i=0;
    for(i=0;i<json.length;i++){
        var cloneDiv= q("a.main-articles-a:first-child").cloneNode(true);
        q("div.main").appendChild(cloneDiv);
        cloneDiv.setAttribute("id","");
        cloneDiv.style.display="inline-block";
        var HTML= cloneDiv.innerHTML;
        HTML=HTML.replace("{{articles-desc}}",json[i].disc);
        HTML=HTML.replace("{{name}}",json[i].name);
        HTML=HTML.replace("{{title}}",json[i].title);
        HTML=HTML.replace("{{date}}",json[i].date);
        HTML=HTML.replace("{{pic}}",json[i].pic_url);
        HTML=HTML.replace("{{num1}}",json[i].num1.toString());
        HTML=HTML.replace("{{num2}}",json[i].num2.toString());
        cloneDiv.innerHTML=HTML;
    }
};
